import { SupportedEmbModels } from "./supportedModels";

export interface EmbTextData {
  "@embText": {
    text: string;
    emb_model?: SupportedEmbModels;
    chunks?: string[]; // This will be auto-generated by the database
  };
}
